import type { Product } from "@/types/product";

export const seedProducts: Product[] = [
  {
    id: "mel-com-propolis",
    name: "Mel com Própolis",
    slug: "mel-com-propolis",
    short_description: "Mel puro com própolis, sabor marcante e combinação especial para o dia a dia.",
    image_url: "/assets/produtos/mel-puro-com-propolis-onda-mel-500g.png",
    category: "Onda Mel",
    weight: "500g",
    tag: "Novidade",
    tag_variant: "dark",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 1
  },
  {
    id: "mel-florada-laranjeira",
    name: "Mel Florada Laranjeira",
    slug: "mel-florada-laranjeira",
    short_description: "Aroma delicado, sabor suave e doçura equilibrada da florada de laranjeira.",
    image_url: "/assets/produtos/mel-florada-laranjeira-500g-onda-mel.png",
    category: "Onda Mel",
    weight: "500g",
    tag: "Floral",
    tag_variant: "soft",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 2
  },
  {
    id: "mel-puro-onda-laranjeira",
    name: "Mel Puro Onda Mel Laranjeira",
    slug: "mel-puro-onda-laranjeira",
    short_description: "Mel puro Onda Mel com florada de laranjeira em embalagem prática de 500g.",
    image_url: "/assets/produtos/mel-puro-onda-laranjeira-500g.png",
    category: "Onda Mel",
    weight: "500g",
    tag: "Floral",
    tag_variant: "soft",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 3
  },
  {
    id: "mel-florada-silvestre",
    name: "Mel Puro Onda Mel Silvestre",
    slug: "mel-florada-silvestre",
    short_description: "O sabor tradicional do mel silvestre para acompanhar receitas, bebidas e momentos especiais.",
    image_url: "/assets/produtos/mel-puro-silvestre-500g-onda-mel.png",
    category: "Onda Mel",
    weight: "500g",
    tag: "Clássico",
    tag_variant: "default",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 4
  },
  {
    id: "favo-de-mel-puro-500g",
    name: "Favo de Mel Puro Onda Mel",
    slug: "favo-de-mel-puro-500g",
    short_description: "Favo de mel puro para quem busca uma experiência natural e diferenciada.",
    image_url: "/assets/produtos/favo-de-mel-puro-500g-onda-mel.jpg",
    category: "Onda Mel",
    weight: "500g",
    tag: "Natural",
    tag_variant: "soft",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 5
  },
  {
    id: "mel-em-sache",
    name: "Mel Puro em Blister Sachê",
    slug: "mel-em-sache",
    short_description: "Porções práticas de mel puro para levar energia natural com você.",
    image_url: "/assets/produtos/mel-puro-blister-sache-onda-mel-32g.png",
    category: "Onda Mel",
    weight: "32g",
    tag: "Prático",
    tag_variant: "blue",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 6
  },
  {
    id: "mel-varias-floradas-sache",
    name: "Mel Várias Floradas em Sachê",
    slug: "mel-varias-floradas-sache",
    short_description: "Sachês de mel várias floradas para consumo rápido, prático e natural.",
    image_url: "/assets/produtos/mel-varias-floradas-sache-32g-onda-mel.png",
    category: "Onda Mel",
    weight: "32g",
    tag: "Prático",
    tag_variant: "blue",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 7
  },
  {
    id: "kit-3-blister-mel-puro-sache",
    name: "Kit 3 Blister Mel Puro Sachê",
    slug: "kit-3-blister-mel-puro-sache",
    short_description: "Kit com 3 blisters de mel puro em sachê Onda Mel para ter sempre por perto.",
    image_url: "/assets/produtos/kit-3-blister-mel-puro-sache-onda-mel-32g.png",
    category: "Onda Mel",
    weight: "3 unidades",
    tag: "Kit",
    tag_variant: "dark",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 8
  },
  {
    id: "propolis-verde-natural-apiario-bonadio",
    name: "Própolis Verde Natural Apiário Bonadio",
    slug: "propolis-verde-natural-apiario-bonadio",
    short_description: "Própolis verde 100% natural em frasco de 30ml, ideal para a rotina de cuidado diário.",
    image_url: "/assets/produtos/propolis-verde-natural-apiario-bonadio-30ml.png",
    category: "Saúde e Bem-estar",
    weight: "30ml",
    tag: "Natural",
    tag_variant: "soft",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 9
  },
  {
    id: "suporte-mesa-celular-tablet-universal",
    name: "Suporte de Mesa para Celular e Tablet",
    slug: "suporte-mesa-celular-tablet-universal",
    short_description: "Suporte universal para celular e tablet, compacto e fácil de usar na mesa.",
    image_url: "/assets/produtos/suporte-mesa-celular-tablet-universal.png",
    category: "Acessórios",
    weight: "Universal",
    tag: "Útil",
    tag_variant: "blue",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 10
  },
  {
    id: "kit-3-suportes-mesa-celular-tablet",
    name: "Kit 3 Suportes de Mesa para Celular e Tablet",
    slug: "kit-3-suportes-mesa-celular-tablet",
    short_description: "Kit com 3 suportes universais para organizar celulares e tablets com praticidade.",
    image_url: "/assets/produtos/kit-3-suportes-mesa-celular-tablet-universal.png",
    category: "Acessórios",
    weight: "3 unidades",
    tag: "Kit",
    tag_variant: "dark",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 11
  },
  {
    id: "copo-termico-inox-473ml",
    name: "Copo Térmico Inox com Tampa e Abridor",
    slug: "copo-termico-inox-473ml",
    short_description: "Copo térmico inox de 473ml com tampa e abridor, mantendo bebidas frias por mais tempo.",
    image_url: "/assets/produtos/copo-termico-inox-473ml-tampa-abridor.png",
    category: "Casa e Utilidades",
    weight: "473ml",
    tag: "Utilidade",
    tag_variant: "default",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 12
  },
  {
    id: "bolsa-gelo-compressa-agua-fria",
    name: "Bolsa de Gelo Compressa Água Fria Ortopédica",
    slug: "bolsa-gelo-compressa-agua-fria",
    short_description: "Bolsa de gelo ortopédica de 200ml para compressas frias com mais conforto.",
    image_url: "/assets/produtos/bolsa-gelo-compressa-agua-fria-ortopedica-200ml.png",
    category: "Saúde e Bem-estar",
    weight: "200ml",
    tag: "Cuidado",
    tag_variant: "blue",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 13
  },
  {
    id: "medidor-de-macarrao-inox",
    name: "Medidor de Macarrão Inox",
    slug: "medidor-de-macarrao-inox",
    short_description: "Medidor de macarrão em inox para facilitar porções e deixar a cozinha mais prática.",
    image_url: "/assets/produtos/medidor-de-macarrao-inox.png",
    category: "Casa e Utilidades",
    weight: "Inox",
    tag: "Cozinha",
    tag_variant: "default",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 14
  },
  {
    id: "organizador-fios-cabos-silicone",
    name: "Organizador de Fios e Cabos de Silicone",
    slug: "organizador-fios-cabos-silicone",
    short_description: "Organizador de silicone para manter fios e cabos alinhados sem bagunça.",
    image_url: "/assets/produtos/organizador-fios-cabos-silicone.png",
    category: "Casa e Utilidades",
    weight: "Silicone",
    tag: "Organização",
    tag_variant: "blue",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 15
  },
  {
    id: "suporte-gancho-cabide-mais-espaco",
    name: "Suporte Gancho para Cabide Mais Espaço",
    slug: "suporte-gancho-cabide-mais-espaco",
    short_description: "Kit com 3 ganchos para cabide, ajudando a ganhar espaço e organizar o armário.",
    image_url: "/assets/produtos/suporte-gancho-cabide-mais-espaco-armario-kit-3.png",
    category: "Casa e Utilidades",
    weight: "Kit com 3",
    tag: "Organização",
    tag_variant: "blue",
    mercado_livre_url: null,
    shopee_url: null,
    whatsapp_url: null,
    is_active: true,
    is_featured: true,
    sort_order: 16
  }
];
